name 'example42-jenkins'
version '2.0.8'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-jenkins'
summary 'Puppet module for jenkins'
description 'This module installs and manages jenkins. Check README for details. Monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
